import './globals.css'
import Header from '@/components/header'
import { Analytics } from "@vercel/analytics/next"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Analytics />
      </body>

    </html>
  )
}
